# --- Etapa 1: Compilación usando Debian Slim ---
FROM node:22-slim AS build

# Instalar dependencias necesarias para Node en Debian
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./

# Aumentamos el límite de memoria para evitar el "Exit handler"
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Instalación ignorando conflictos de peer-dependencies
RUN npm install --legacy-peer-deps --no-audit

COPY . .
RUN npm run build -- --configuration=production

# --- Etapa 2: Servidor ---
FROM nginx:1.29-alpine
COPY --from=build /app/dist/portal-syslab-angular/browser /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]